version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
  web:
    build: .
    depends_on:
      - mongo
    networks:
      - app-tier
    ports:
     - "8087:8087"
networks:
  app-tier:
    driver: bridge
